# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/enum_csv/all/enum_csv.rbi
#
# enum_csv-1.1.0

module EnumCSV
  def csv(enum, opts = nil); end
  def self.csv(enum, opts = nil); end
end
