# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/humanize/all/humanize.rbi
#
# humanize-2.4.0

module Humanize
  def humanize(locale: nil, decimals_as: nil); end
  def process_decimals(locale_class, locale, parts, decimals_as, spacer); end
  def self.config; end
  def self.config=(arg0); end
  def self.configure; end
  def self.for_locale(locale); end
  def self.locale_is?(locale); end
  def self.reset_config; end
  def self.stringify(parts, sign, spacer); end
end
class Humanize::Configuration
  def decimals_as; end
  def decimals_as=(arg0); end
  def default_locale; end
  def default_locale=(arg0); end
  def initialize; end
end
class Integer < Numeric
  include Humanize
end
class Float < Numeric
  include Humanize
end
class BigDecimal < Numeric
  include Humanize
end
