# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth-facebook/all/omniauth-facebook.rbi
#
# omniauth-facebook-4.0.0

module OmniAuth
end
module OmniAuth::Facebook
end
class OmniAuth::Facebook::SignedRequest
  def base64_decode_url(value); end
  def initialize(value, secret); end
  def parse_signed_request; end
  def payload; end
  def secret; end
  def self.parse(value, secret); end
  def valid_signature?(signature, payload, algorithm = nil); end
  def value; end
end
class OmniAuth::Facebook::SignedRequest::UnknownSignatureAlgorithmError < NotImplementedError
end
module OmniAuth::Strategies
end
class OmniAuth::Strategies::Facebook < OmniAuth::Strategies::OAuth2
  def access_token_options; end
  def appsecret_proof; end
  def authorize_params; end
  def build_access_token; end
  def callback_phase; end
  def callback_url; end
  def image_url(uid, options); end
  def info_options; end
  def prune!(hash); end
  def raw_info; end
  def raw_signed_request_from_cookie; end
  def signed_request_from_cookie; end
  def with_authorization_code!; end
  extend OmniAuth::Strategy::ClassMethods
end
class OmniAuth::Strategies::Facebook::NoAuthorizationCodeError < StandardError
end
