# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-ssl-enforcer/all/rack-ssl-enforcer.rbi
#
# rack-ssl-enforcer-0.2.9

class SslEnforcerConstraint
  def initialize(name, rule, request); end
  def matches?; end
  def negate_result?; end
  def operator; end
  def tested_string; end
end
module Rack
end
class Rack::SslEnforcer
  def adjust_port_to(scheme); end
  def call(env); end
  def call_before_redirect; end
  def current_scheme; end
  def destination_host; end
  def enforce_non_ssl?; end
  def enforce_ssl?; end
  def enforce_ssl_for?(keys); end
  def flag_cookies_as_secure!(headers); end
  def host_mismatch?; end
  def ignore?; end
  def initialize(app, options = nil); end
  def modify_location_and_redirect; end
  def redirect_required?; end
  def redirect_to(location); end
  def replace_host(uri, host); end
  def replace_scheme(uri, scheme); end
  def scheme_mismatch?; end
  def set_hsts_headers!(headers); end
  def ssl_request?; end
end
