# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rqrcode/all/rqrcode.rbi
#
# rqrcode-1.1.2

module RQRCode
end
class RQRCode::QRCode
  def initialize(string, *args); end
  def modules(*args, &block); end
  def qrcode; end
  def to_s(*args, &block); end
  extend Forwardable
  include RQRCode::Export::ANSI
  include RQRCode::Export::HTML
  include RQRCode::Export::PNG
  include RQRCode::Export::SVG
end
module RQRCode::Export
end
module RQRCode::Export::ANSI
  def as_ansi(options = nil); end
end
module RQRCode::Export::HTML
  def as_html; end
  def rows; end
end
class Anonymous_Struct_36 < Struct
  def qr; end
  def qr=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class RQRCode::Export::HTML::Rows < Anonymous_Struct_36
  def as_html; end
  def rows; end
end
class Anonymous_Struct_37 < Struct
  def qr; end
  def qr=(_); end
  def qr_module; end
  def qr_module=(_); end
  def row_index; end
  def row_index=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class RQRCode::Export::HTML::Row < Anonymous_Struct_37
  def as_html; end
  def cells; end
end
class Anonymous_Struct_38 < Struct
  def col_index; end
  def col_index=(_); end
  def qr; end
  def qr=(_); end
  def row_index; end
  def row_index=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class RQRCode::Export::HTML::Cell < Anonymous_Struct_38
  def as_html; end
  def html_class; end
end
module RQRCode::Export::PNG
  def as_png(options = nil); end
end
module RQRCode::Export::SVG
  def as_svg(options = nil); end
end
