# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sinatra-cross_origin/all/sinatra-cross_origin.rbi
#
# sinatra-cross_origin-0.4.0

module Sinatra
end
module Sinatra::CrossOrigin
  def self.registered(app); end
end
module Sinatra::CrossOrigin::Helpers
  def cross_origin(hash = nil); end
end
