source "https://rubygems.org"

ruby "3.2.2"

gem "rake", ">= 12.3.3"
gem 'rack', '>= 2.0.8'
gem 'sinatra', '>= 2.0.2'
gem 'stripe'
gem 'slim'
gem 'json'
gem 'thin'
gem 'sequel'
gem 'sequel_pg'
gem 'shrine'
gem 'pg'
gem 'bigdecimal'
gem 'aws-sdk'
gem 'image_processing'
gem 'mini_magick', '>= 4.9.4'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'postmark'
gem 'bcrypt'
gem 'autoforme'
gem 'ice_cube', '>= 0.16.3'
gem 'rest-client'
gem 'activesupport'
gem 'rack-ssl-enforcer'
gem 'icalendar'
gem 'eventbrite_sdk'
gem 'koala'
gem 'sucker_punch'
gem 'humanize'
gem 'rqrcode'
gem 'sinatra-cross_origin'
gem 'sinatra-contrib'
gem 'jwt'
gem 'braintree'
gem 'paypal-payouts-sdk'
gem 'paypal-sdk-rest'
gem 'rack-contrib'
gem 'tzinfo'
gem 'tzinfo-data'
gem "addressable", ">= 2.8.0"
gem "nokogiri", ">= 1.12.5"
gem "rexml", ">= 3.2.5"

gem 'slack-ruby-client'
gem 'twilio-ruby'

gem 'google_drive', '>= 2.1.5'
gem 'google-api-client'
gem 'google-apis-calendar_v3'
gem 'google-apis-sheets_v4'
gem 'googleauth'
