source "https://rubygems.org"

ruby "2.5.0"

gem 'rack', '>= 2.0.6'
gem 'sinatra', '>= 2.0.2'
gem 'stripe'
gem 'slim'
gem 'json'
gem 'thin'
gem 'google-api-client'
gem 'sequel'
gem 'shrine'
gem 'pg'
gem 'aws-sdk'
gem 'image_processing'
gem 'mini_magick', '>= 4.9.4'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'postmark'
gem 'bcrypt'
gem 'autoforme'
gem 'ice_cube', '>= 0.16.3'
gem 'rest-client'
gem 'twilio-ruby', '~> 5.26.0'
gem 'activesupport'
gem 'rack-ssl-enforcer'
gem 'icalendar'
gem 'eventbrite_sdk'
gem 'koala'
gem 'sucker_punch'
gem 'humanize'
gem 'rqrcode'
gem 'google_drive'