source "https://rubygems.org"

gem 'sinatra'
gem 'stripe'
gem 'slim'
gem 'json'
gem 'thin'
gem 'google-api-client'
gem 'sequel'
gem 'shrine'
gem 'pg'
gem 'aws-sdk'
gem 'image_processing'
gem 'mini_magick', '>= 4.3.5'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'postmark'
gem 'bcrypt'
gem 'autoforme'
gem 'ice_cube'